//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyMaker_Online.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_add", ReplyAction="http://tempuri.org/IService1/Income_History_addResponse")]
        void Income_History_add(int userid, string description, int income, string date, int type, int ID, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_add", ReplyAction="http://tempuri.org/IService1/Income_History_addResponse")]
        System.Threading.Tasks.Task Income_History_addAsync(int userid, string description, int income, string date, int type, int ID, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_selectsingle", ReplyAction="http://tempuri.org/IService1/Income_History_selectsingleResponse")]
        System.Data.DataTable Income_History_selectsingle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_selectsingle", ReplyAction="http://tempuri.org/IService1/Income_History_selectsingleResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Income_History_selectsingleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_selectspecific", ReplyAction="http://tempuri.org/IService1/Income_History_selectspecificResponse")]
        System.Data.DataTable Income_History_selectspecific(int userid, string des, int income, string date1, string date2, int type, int ID, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_selectspecific", ReplyAction="http://tempuri.org/IService1/Income_History_selectspecificResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Income_History_selectspecificAsync(int userid, string des, int income, string date1, string date2, int type, int ID, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_selectbyuser", ReplyAction="http://tempuri.org/IService1/Income_History_selectbyuserResponse")]
        System.Data.DataTable Income_History_selectbyuser(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_selectbyuser", ReplyAction="http://tempuri.org/IService1/Income_History_selectbyuserResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Income_History_selectbyuserAsync(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_update", ReplyAction="http://tempuri.org/IService1/Income_History_updateResponse")]
        void Income_History_update(int id, string description, int income, string date, int type, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_update", ReplyAction="http://tempuri.org/IService1/Income_History_updateResponse")]
        System.Threading.Tasks.Task Income_History_updateAsync(int id, string description, int income, string date, int type, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_delete", ReplyAction="http://tempuri.org/IService1/Income_History_deleteResponse")]
        void Income_History_delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_delete", ReplyAction="http://tempuri.org/IService1/Income_History_deleteResponse")]
        System.Threading.Tasks.Task Income_History_deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_getall", ReplyAction="http://tempuri.org/IService1/Income_History_getallResponse")]
        System.Data.DataTable Income_History_getall(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_getall", ReplyAction="http://tempuri.org/IService1/Income_History_getallResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Income_History_getallAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_get_money", ReplyAction="http://tempuri.org/IService1/Income_History_get_moneyResponse")]
        int Income_History_get_money(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_get_money", ReplyAction="http://tempuri.org/IService1/Income_History_get_moneyResponse")]
        System.Threading.Tasks.Task<int> Income_History_get_moneyAsync(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_get_monthly_money", ReplyAction="http://tempuri.org/IService1/Income_History_get_monthly_moneyResponse")]
        int Income_History_get_monthly_money(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_get_monthly_money", ReplyAction="http://tempuri.org/IService1/Income_History_get_monthly_moneyResponse")]
        System.Threading.Tasks.Task<int> Income_History_get_monthly_moneyAsync(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_get_monthly_history", ReplyAction="http://tempuri.org/IService1/Income_History_get_monthly_historyResponse")]
        System.Data.DataTable Income_History_get_monthly_history(int userid, int monthlyid, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_get_monthly_history", ReplyAction="http://tempuri.org/IService1/Income_History_get_monthly_historyResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Income_History_get_monthly_historyAsync(int userid, int monthlyid, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_clean_user_data", ReplyAction="http://tempuri.org/IService1/Income_History_clean_user_dataResponse")]
        void Income_History_clean_user_data(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Income_History_clean_user_data", ReplyAction="http://tempuri.org/IService1/Income_History_clean_user_dataResponse")]
        System.Threading.Tasks.Task Income_History_clean_user_dataAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_add", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_addResponse")]
        void Monthly_Expenses_add(int userid, int averaged_price, string product, int num_payments, int total_payed, int product_type, string date, int Payments, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_add", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_addResponse")]
        System.Threading.Tasks.Task Monthly_Expenses_addAsync(int userid, int averaged_price, string product, int num_payments, int total_payed, int product_type, string date, int Payments, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_delete", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_deleteResponse")]
        void Monthly_Expenses_delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_delete", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_deleteResponse")]
        System.Threading.Tasks.Task Monthly_Expenses_deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_change", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_changeResponse")]
        void Monthly_Expenses_change(int id, int averaged_price, string product, int num_payments, int total_payed, int product_type, string dateou, int payments, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_change", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_changeResponse")]
        System.Threading.Tasks.Task Monthly_Expenses_changeAsync(int id, int averaged_price, string product, int num_payments, int total_payed, int product_type, string dateou, int payments, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_getsingle", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_getsingleResponse")]
        System.Data.DataTable Monthly_Expenses_getsingle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_getsingle", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_getsingleResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Expenses_getsingleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_getall", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_getallResponse")]
        System.Data.DataTable Monthly_Expenses_getall(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_getall", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_getallResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Expenses_getallAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_repeat", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_repeatResponse")]
        void Monthly_Expenses_repeat(int id, string date, int addprice, bool ispayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_repeat", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_repeatResponse")]
        System.Threading.Tasks.Task Monthly_Expenses_repeatAsync(int id, string date, int addprice, bool ispayment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_Getmoutcome", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_GetmoutcomeResponse")]
        System.Data.DataTable Monthly_Expenses_Getmoutcome(int userid, string product, int money, int type, string date1, string date2, int payments, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_Getmoutcome", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_GetmoutcomeResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Expenses_GetmoutcomeAsync(int userid, string product, int money, int type, string date1, string date2, int payments, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_clean_user_data", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_clean_user_dataResponse")]
        void Monthly_Expenses_clean_user_data(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_clean_user_data", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_clean_user_dataResponse")]
        System.Threading.Tasks.Task Monthly_Expenses_clean_user_dataAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_get_to_add_price", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_get_to_add_priceResponse")]
        System.Data.DataTable Monthly_Expenses_get_to_add_price(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_get_to_add_price", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_get_to_add_priceResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Expenses_get_to_add_priceAsync(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_getaverage", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_getaverageResponse")]
        int Monthly_Expenses_getaverage(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Expenses_getaverage", ReplyAction="http://tempuri.org/IService1/Monthly_Expenses_getaverageResponse")]
        System.Threading.Tasks.Task<int> Monthly_Expenses_getaverageAsync(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_Add", ReplyAction="http://tempuri.org/IService1/Monthly_Income_AddResponse")]
        void Monthly_Income_Add(int cpm, string des, int userid, int totalpayed, int numofpay, string date, int type, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_Add", ReplyAction="http://tempuri.org/IService1/Monthly_Income_AddResponse")]
        System.Threading.Tasks.Task Monthly_Income_AddAsync(int cpm, string des, int userid, int totalpayed, int numofpay, string date, int type, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_getall", ReplyAction="http://tempuri.org/IService1/Monthly_Income_getallResponse")]
        System.Data.DataTable Monthly_Income_getall(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_getall", ReplyAction="http://tempuri.org/IService1/Monthly_Income_getallResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Income_getallAsync(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_getspecific", ReplyAction="http://tempuri.org/IService1/Monthly_Income_getspecificResponse")]
        System.Data.DataTable Monthly_Income_getspecific(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_getspecific", ReplyAction="http://tempuri.org/IService1/Monthly_Income_getspecificResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Income_getspecificAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_Repeat", ReplyAction="http://tempuri.org/IService1/Monthly_Income_RepeatResponse")]
        void Monthly_Income_Repeat(int ID, string date, int addprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_Repeat", ReplyAction="http://tempuri.org/IService1/Monthly_Income_RepeatResponse")]
        System.Threading.Tasks.Task Monthly_Income_RepeatAsync(int ID, string date, int addprice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_Getmincome", ReplyAction="http://tempuri.org/IService1/Monthly_Income_GetmincomeResponse")]
        System.Data.DataTable Monthly_Income_Getmincome(int userid, string des, int cpm, string date1, string date2, int type, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_Getmincome", ReplyAction="http://tempuri.org/IService1/Monthly_Income_GetmincomeResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Income_GetmincomeAsync(int userid, string des, int cpm, string date1, string date2, int type, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_change", ReplyAction="http://tempuri.org/IService1/Monthly_Income_changeResponse")]
        void Monthly_Income_change(int monthlyid, int cashpermonth, string description, int totalpay, int numofpay, string dateou, int type, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_change", ReplyAction="http://tempuri.org/IService1/Monthly_Income_changeResponse")]
        System.Threading.Tasks.Task Monthly_Income_changeAsync(int monthlyid, int cashpermonth, string description, int totalpay, int numofpay, string dateou, int type, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_delete", ReplyAction="http://tempuri.org/IService1/Monthly_Income_deleteResponse")]
        void Monthly_Income_delete(int monthlyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_delete", ReplyAction="http://tempuri.org/IService1/Monthly_Income_deleteResponse")]
        System.Threading.Tasks.Task Monthly_Income_deleteAsync(int monthlyid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_clean_user_data", ReplyAction="http://tempuri.org/IService1/Monthly_Income_clean_user_dataResponse")]
        void Monthly_Income_clean_user_data(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_clean_user_data", ReplyAction="http://tempuri.org/IService1/Monthly_Income_clean_user_dataResponse")]
        System.Threading.Tasks.Task Monthly_Income_clean_user_dataAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_get_to_add_price", ReplyAction="http://tempuri.org/IService1/Monthly_Income_get_to_add_priceResponse")]
        System.Data.DataTable Monthly_Income_get_to_add_price(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_get_to_add_price", ReplyAction="http://tempuri.org/IService1/Monthly_Income_get_to_add_priceResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Income_get_to_add_priceAsync(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_getaverage", ReplyAction="http://tempuri.org/IService1/Monthly_Income_getaverageResponse")]
        int Monthly_Income_getaverage(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Monthly_Income_getaverage", ReplyAction="http://tempuri.org/IService1/Monthly_Income_getaverageResponse")]
        System.Threading.Tasks.Task<int> Monthly_Income_getaverageAsync(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_AddProduct", ReplyAction="http://tempuri.org/IService1/Outcome_History_AddProductResponse")]
        void Outcome_History_AddProduct(int userid, int typeid, int price, string product, string date, int ID, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_AddProduct", ReplyAction="http://tempuri.org/IService1/Outcome_History_AddProductResponse")]
        System.Threading.Tasks.Task Outcome_History_AddProductAsync(int userid, int typeid, int price, string product, string date, int ID, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_selectbyuser", ReplyAction="http://tempuri.org/IService1/Outcome_History_selectbyuserResponse")]
        System.Data.DataTable Outcome_History_selectbyuser(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_selectbyuser", ReplyAction="http://tempuri.org/IService1/Outcome_History_selectbyuserResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Outcome_History_selectbyuserAsync(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_selectbypro", ReplyAction="http://tempuri.org/IService1/Outcome_History_selectbyproResponse")]
        System.Data.DataTable Outcome_History_selectbypro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_selectbypro", ReplyAction="http://tempuri.org/IService1/Outcome_History_selectbyproResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Outcome_History_selectbyproAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_Getproducts", ReplyAction="http://tempuri.org/IService1/Outcome_History_GetproductsResponse")]
        System.Data.DataTable Outcome_History_Getproducts(int userid, int typeid, int price, string product, string date1, string date2, int ID, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_Getproducts", ReplyAction="http://tempuri.org/IService1/Outcome_History_GetproductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Outcome_History_GetproductsAsync(int userid, int typeid, int price, string product, string date1, string date2, int ID, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_SetProduct", ReplyAction="http://tempuri.org/IService1/Outcome_History_SetProductResponse")]
        void Outcome_History_SetProduct(int proid, int typeid, int price, string product, string date, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_SetProduct", ReplyAction="http://tempuri.org/IService1/Outcome_History_SetProductResponse")]
        System.Threading.Tasks.Task Outcome_History_SetProductAsync(int proid, int typeid, int price, string product, string date, string typegroup, string typestring);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_delete", ReplyAction="http://tempuri.org/IService1/Outcome_History_deleteResponse")]
        void Outcome_History_delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_delete", ReplyAction="http://tempuri.org/IService1/Outcome_History_deleteResponse")]
        System.Threading.Tasks.Task Outcome_History_deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_get_money", ReplyAction="http://tempuri.org/IService1/Outcome_History_get_moneyResponse")]
        int Outcome_History_get_money(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_get_money", ReplyAction="http://tempuri.org/IService1/Outcome_History_get_moneyResponse")]
        System.Threading.Tasks.Task<int> Outcome_History_get_moneyAsync(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_get_monthly_money", ReplyAction="http://tempuri.org/IService1/Outcome_History_get_monthly_moneyResponse")]
        int Outcome_History_get_monthly_money(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_get_monthly_money", ReplyAction="http://tempuri.org/IService1/Outcome_History_get_monthly_moneyResponse")]
        System.Threading.Tasks.Task<int> Outcome_History_get_monthly_moneyAsync(int userid, string date1, string date2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_get_monthly_history", ReplyAction="http://tempuri.org/IService1/Outcome_History_get_monthly_historyResponse")]
        System.Data.DataTable Outcome_History_get_monthly_history(int userid, int monthlyid, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_get_monthly_history", ReplyAction="http://tempuri.org/IService1/Outcome_History_get_monthly_historyResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Outcome_History_get_monthly_historyAsync(int userid, int monthlyid, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_clean_user_data", ReplyAction="http://tempuri.org/IService1/Outcome_History_clean_user_dataResponse")]
        void Outcome_History_clean_user_data(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Outcome_History_clean_user_data", ReplyAction="http://tempuri.org/IService1/Outcome_History_clean_user_dataResponse")]
        System.Threading.Tasks.Task Outcome_History_clean_user_dataAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Type_Group_Suggestion_add", ReplyAction="http://tempuri.org/IService1/Type_Group_Suggestion_addResponse")]
        void Type_Group_Suggestion_add(int userid, string type_group, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Type_Group_Suggestion_add", ReplyAction="http://tempuri.org/IService1/Type_Group_Suggestion_addResponse")]
        System.Threading.Tasks.Task Type_Group_Suggestion_addAsync(int userid, string type_group, string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Type_Group_Suggestion_select", ReplyAction="http://tempuri.org/IService1/Type_Group_Suggestion_selectResponse")]
        System.Data.DataTable Type_Group_Suggestion_select(int id, int userid, string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Type_Group_Suggestion_select", ReplyAction="http://tempuri.org/IService1/Type_Group_Suggestion_selectResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Type_Group_Suggestion_selectAsync(int id, int userid, string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Type_Group_Suggestion_getall", ReplyAction="http://tempuri.org/IService1/Type_Group_Suggestion_getallResponse")]
        System.Data.DataTable Type_Group_Suggestion_getall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Type_Group_Suggestion_getall", ReplyAction="http://tempuri.org/IService1/Type_Group_Suggestion_getallResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Type_Group_Suggestion_getallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Type_Group_Suggestion_delete", ReplyAction="http://tempuri.org/IService1/Type_Group_Suggestion_deleteResponse")]
        void Type_Group_Suggestion_delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Type_Group_Suggestion_delete", ReplyAction="http://tempuri.org/IService1/Type_Group_Suggestion_deleteResponse")]
        System.Threading.Tasks.Task Type_Group_Suggestion_deleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_add", ReplyAction="http://tempuri.org/IService1/Types_addResponse")]
        void Types_add(string type, string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_add", ReplyAction="http://tempuri.org/IService1/Types_addResponse")]
        System.Threading.Tasks.Task Types_addAsync(string type, string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_add_Group", ReplyAction="http://tempuri.org/IService1/Types_add_GroupResponse")]
        void Types_add_Group(string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_add_Group", ReplyAction="http://tempuri.org/IService1/Types_add_GroupResponse")]
        System.Threading.Tasks.Task Types_add_GroupAsync(string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_gettype", ReplyAction="http://tempuri.org/IService1/Types_gettypeResponse")]
        System.Data.DataTable Types_gettype(int id, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_gettype", ReplyAction="http://tempuri.org/IService1/Types_gettypeResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Types_gettypeAsync(int id, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_getall", ReplyAction="http://tempuri.org/IService1/Types_getallResponse")]
        System.Data.DataTable Types_getall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_getall", ReplyAction="http://tempuri.org/IService1/Types_getallResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Types_getallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_getid", ReplyAction="http://tempuri.org/IService1/Types_getidResponse")]
        int Types_getid(string type, string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_getid", ReplyAction="http://tempuri.org/IService1/Types_getidResponse")]
        System.Threading.Tasks.Task<int> Types_getidAsync(string type, string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_gettypestring", ReplyAction="http://tempuri.org/IService1/Types_gettypestringResponse")]
        string Types_gettypestring(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_gettypestring", ReplyAction="http://tempuri.org/IService1/Types_gettypestringResponse")]
        System.Threading.Tasks.Task<string> Types_gettypestringAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_checkduplicate", ReplyAction="http://tempuri.org/IService1/Types_checkduplicateResponse")]
        bool Types_checkduplicate(string newtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_checkduplicate", ReplyAction="http://tempuri.org/IService1/Types_checkduplicateResponse")]
        System.Threading.Tasks.Task<bool> Types_checkduplicateAsync(string newtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_checkduplicategroups", ReplyAction="http://tempuri.org/IService1/Types_checkduplicategroupsResponse")]
        bool Types_checkduplicategroups(string typegroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_checkduplicategroups", ReplyAction="http://tempuri.org/IService1/Types_checkduplicategroupsResponse")]
        System.Threading.Tasks.Task<bool> Types_checkduplicategroupsAsync(string typegroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_all_groups", ReplyAction="http://tempuri.org/IService1/Types_get_all_groupsResponse")]
        System.Data.DataTable Types_get_all_groups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_all_groups", ReplyAction="http://tempuri.org/IService1/Types_get_all_groupsResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Types_get_all_groupsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_all_types_in_group", ReplyAction="http://tempuri.org/IService1/Types_get_all_types_in_groupResponse")]
        System.Data.DataTable Types_get_all_types_in_group(string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_all_types_in_group", ReplyAction="http://tempuri.org/IService1/Types_get_all_types_in_groupResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Types_get_all_types_in_groupAsync(string group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_group", ReplyAction="http://tempuri.org/IService1/Types_get_groupResponse")]
        string Types_get_group(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_group", ReplyAction="http://tempuri.org/IService1/Types_get_groupResponse")]
        System.Threading.Tasks.Task<string> Types_get_groupAsync(string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_gettypegroupstring", ReplyAction="http://tempuri.org/IService1/Types_gettypegroupstringResponse")]
        string Types_gettypegroupstring(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_gettypegroupstring", ReplyAction="http://tempuri.org/IService1/Types_gettypegroupstringResponse")]
        System.Threading.Tasks.Task<string> Types_gettypegroupstringAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_gettypeItemstring", ReplyAction="http://tempuri.org/IService1/Types_gettypeItemstringResponse")]
        string Types_gettypeItemstring(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_gettypeItemstring", ReplyAction="http://tempuri.org/IService1/Types_gettypeItemstringResponse")]
        System.Threading.Tasks.Task<string> Types_gettypeItemstringAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_group_table", ReplyAction="http://tempuri.org/IService1/Types_get_group_tableResponse")]
        System.Data.DataTable Types_get_group_table(string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_group_table", ReplyAction="http://tempuri.org/IService1/Types_get_group_tableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Types_get_group_tableAsync(string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_specific_types", ReplyAction="http://tempuri.org/IService1/Types_get_specific_typesResponse")]
        System.Data.DataTable Types_get_specific_types(string type, string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Types_get_specific_types", ReplyAction="http://tempuri.org/IService1/Types_get_specific_typesResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Types_get_specific_typesAsync(string type, string type_group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_Register", ReplyAction="http://tempuri.org/IService1/Users_RegisterResponse")]
        void Users_Register(string fname, string lname, string password, int money, string mtype, string date, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_Register", ReplyAction="http://tempuri.org/IService1/Users_RegisterResponse")]
        System.Threading.Tasks.Task Users_RegisterAsync(string fname, string lname, string password, int money, string mtype, string date, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_Login", ReplyAction="http://tempuri.org/IService1/Users_LoginResponse")]
        int Users_Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_Login", ReplyAction="http://tempuri.org/IService1/Users_LoginResponse")]
        System.Threading.Tasks.Task<int> Users_LoginAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getall", ReplyAction="http://tempuri.org/IService1/Users_getallResponse")]
        System.Data.DataTable Users_getall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getall", ReplyAction="http://tempuri.org/IService1/Users_getallResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Users_getallAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getpassword", ReplyAction="http://tempuri.org/IService1/Users_getpasswordResponse")]
        string Users_getpassword(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getpassword", ReplyAction="http://tempuri.org/IService1/Users_getpasswordResponse")]
        System.Threading.Tasks.Task<string> Users_getpasswordAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_get_specific", ReplyAction="http://tempuri.org/IService1/Users_get_specificResponse")]
        System.Data.DataTable Users_get_specific(string fname, string lname, string pass, int money1, int money2, string moneytype, string date1, string date2, bool admin, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_get_specific", ReplyAction="http://tempuri.org/IService1/Users_get_specificResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Users_get_specificAsync(string fname, string lname, string pass, int money1, int money2, string moneytype, string date1, string date2, bool admin, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_Change", ReplyAction="http://tempuri.org/IService1/Users_ChangeResponse")]
        void Users_Change(int id, string fname, string lname, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_Change", ReplyAction="http://tempuri.org/IService1/Users_ChangeResponse")]
        System.Threading.Tasks.Task Users_ChangeAsync(int id, string fname, string lname, string password, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_addmoney", ReplyAction="http://tempuri.org/IService1/Users_addmoneyResponse")]
        void Users_addmoney(int toadd, int userid, char ioro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_addmoney", ReplyAction="http://tempuri.org/IService1/Users_addmoneyResponse")]
        System.Threading.Tasks.Task Users_addmoneyAsync(int toadd, int userid, char ioro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getmoney", ReplyAction="http://tempuri.org/IService1/Users_getmoneyResponse")]
        int Users_getmoney(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getmoney", ReplyAction="http://tempuri.org/IService1/Users_getmoneyResponse")]
        System.Threading.Tasks.Task<int> Users_getmoneyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_get_user_reg_date", ReplyAction="http://tempuri.org/IService1/Users_get_user_reg_dateResponse")]
        System.DateTime Users_get_user_reg_date(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_get_user_reg_date", ReplyAction="http://tempuri.org/IService1/Users_get_user_reg_dateResponse")]
        System.Threading.Tasks.Task<System.DateTime> Users_get_user_reg_dateAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_is_admin", ReplyAction="http://tempuri.org/IService1/Users_is_adminResponse")]
        bool Users_is_admin(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_is_admin", ReplyAction="http://tempuri.org/IService1/Users_is_adminResponse")]
        System.Threading.Tasks.Task<bool> Users_is_adminAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_make_admin", ReplyAction="http://tempuri.org/IService1/Users_make_adminResponse")]
        void Users_make_admin(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_make_admin", ReplyAction="http://tempuri.org/IService1/Users_make_adminResponse")]
        System.Threading.Tasks.Task Users_make_adminAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_nomake_admin", ReplyAction="http://tempuri.org/IService1/Users_nomake_adminResponse")]
        void Users_nomake_admin(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_nomake_admin", ReplyAction="http://tempuri.org/IService1/Users_nomake_adminResponse")]
        System.Threading.Tasks.Task Users_nomake_adminAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_clean_user_data", ReplyAction="http://tempuri.org/IService1/Users_clean_user_dataResponse")]
        void Users_clean_user_data(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_clean_user_data", ReplyAction="http://tempuri.org/IService1/Users_clean_user_dataResponse")]
        System.Threading.Tasks.Task Users_clean_user_dataAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getallincome", ReplyAction="http://tempuri.org/IService1/Users_getallincomeResponse")]
        int Users_getallincome(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getallincome", ReplyAction="http://tempuri.org/IService1/Users_getallincomeResponse")]
        System.Threading.Tasks.Task<int> Users_getallincomeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getalloutcome", ReplyAction="http://tempuri.org/IService1/Users_getalloutcomeResponse")]
        int Users_getalloutcome(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_getalloutcome", ReplyAction="http://tempuri.org/IService1/Users_getalloutcomeResponse")]
        System.Threading.Tasks.Task<int> Users_getalloutcomeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_check_email_duplicate", ReplyAction="http://tempuri.org/IService1/Users_check_email_duplicateResponse")]
        bool Users_check_email_duplicate(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_check_email_duplicate", ReplyAction="http://tempuri.org/IService1/Users_check_email_duplicateResponse")]
        System.Threading.Tasks.Task<bool> Users_check_email_duplicateAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getaddress", ReplyAction="http://tempuri.org/IService1/getaddressResponse")]
        void getaddress(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getaddress", ReplyAction="http://tempuri.org/IService1/getaddressResponse")]
        System.Threading.Tasks.Task getaddressAsync(string path);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MoneyMaker_Online.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MoneyMaker_Online.ServiceReference.IService1>, MoneyMaker_Online.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public void Income_History_add(int userid, string description, int income, string date, int type, int ID, string typegroup, string typestring) {
            base.Channel.Income_History_add(userid, description, income, date, type, ID, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task Income_History_addAsync(int userid, string description, int income, string date, int type, int ID, string typegroup, string typestring) {
            return base.Channel.Income_History_addAsync(userid, description, income, date, type, ID, typegroup, typestring);
        }
        
        public System.Data.DataTable Income_History_selectsingle(int id) {
            return base.Channel.Income_History_selectsingle(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Income_History_selectsingleAsync(int id) {
            return base.Channel.Income_History_selectsingleAsync(id);
        }
        
        public System.Data.DataTable Income_History_selectspecific(int userid, string des, int income, string date1, string date2, int type, int ID, string typegroup, string typestring) {
            return base.Channel.Income_History_selectspecific(userid, des, income, date1, date2, type, ID, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Income_History_selectspecificAsync(int userid, string des, int income, string date1, string date2, int type, int ID, string typegroup, string typestring) {
            return base.Channel.Income_History_selectspecificAsync(userid, des, income, date1, date2, type, ID, typegroup, typestring);
        }
        
        public System.Data.DataTable Income_History_selectbyuser(int userid) {
            return base.Channel.Income_History_selectbyuser(userid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Income_History_selectbyuserAsync(int userid) {
            return base.Channel.Income_History_selectbyuserAsync(userid);
        }
        
        public void Income_History_update(int id, string description, int income, string date, int type, string typegroup, string typestring) {
            base.Channel.Income_History_update(id, description, income, date, type, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task Income_History_updateAsync(int id, string description, int income, string date, int type, string typegroup, string typestring) {
            return base.Channel.Income_History_updateAsync(id, description, income, date, type, typegroup, typestring);
        }
        
        public void Income_History_delete(int id) {
            base.Channel.Income_History_delete(id);
        }
        
        public System.Threading.Tasks.Task Income_History_deleteAsync(int id) {
            return base.Channel.Income_History_deleteAsync(id);
        }
        
        public System.Data.DataTable Income_History_getall(int id) {
            return base.Channel.Income_History_getall(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Income_History_getallAsync(int id) {
            return base.Channel.Income_History_getallAsync(id);
        }
        
        public int Income_History_get_money(int userid, string date1, string date2) {
            return base.Channel.Income_History_get_money(userid, date1, date2);
        }
        
        public System.Threading.Tasks.Task<int> Income_History_get_moneyAsync(int userid, string date1, string date2) {
            return base.Channel.Income_History_get_moneyAsync(userid, date1, date2);
        }
        
        public int Income_History_get_monthly_money(int userid, string date1, string date2) {
            return base.Channel.Income_History_get_monthly_money(userid, date1, date2);
        }
        
        public System.Threading.Tasks.Task<int> Income_History_get_monthly_moneyAsync(int userid, string date1, string date2) {
            return base.Channel.Income_History_get_monthly_moneyAsync(userid, date1, date2);
        }
        
        public System.Data.DataTable Income_History_get_monthly_history(int userid, int monthlyid, string date) {
            return base.Channel.Income_History_get_monthly_history(userid, monthlyid, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Income_History_get_monthly_historyAsync(int userid, int monthlyid, string date) {
            return base.Channel.Income_History_get_monthly_historyAsync(userid, monthlyid, date);
        }
        
        public void Income_History_clean_user_data(int id) {
            base.Channel.Income_History_clean_user_data(id);
        }
        
        public System.Threading.Tasks.Task Income_History_clean_user_dataAsync(int id) {
            return base.Channel.Income_History_clean_user_dataAsync(id);
        }
        
        public void Monthly_Expenses_add(int userid, int averaged_price, string product, int num_payments, int total_payed, int product_type, string date, int Payments, string typegroup, string typestring) {
            base.Channel.Monthly_Expenses_add(userid, averaged_price, product, num_payments, total_payed, product_type, date, Payments, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task Monthly_Expenses_addAsync(int userid, int averaged_price, string product, int num_payments, int total_payed, int product_type, string date, int Payments, string typegroup, string typestring) {
            return base.Channel.Monthly_Expenses_addAsync(userid, averaged_price, product, num_payments, total_payed, product_type, date, Payments, typegroup, typestring);
        }
        
        public void Monthly_Expenses_delete(int id) {
            base.Channel.Monthly_Expenses_delete(id);
        }
        
        public System.Threading.Tasks.Task Monthly_Expenses_deleteAsync(int id) {
            return base.Channel.Monthly_Expenses_deleteAsync(id);
        }
        
        public void Monthly_Expenses_change(int id, int averaged_price, string product, int num_payments, int total_payed, int product_type, string dateou, int payments, string typegroup, string typestring) {
            base.Channel.Monthly_Expenses_change(id, averaged_price, product, num_payments, total_payed, product_type, dateou, payments, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task Monthly_Expenses_changeAsync(int id, int averaged_price, string product, int num_payments, int total_payed, int product_type, string dateou, int payments, string typegroup, string typestring) {
            return base.Channel.Monthly_Expenses_changeAsync(id, averaged_price, product, num_payments, total_payed, product_type, dateou, payments, typegroup, typestring);
        }
        
        public System.Data.DataTable Monthly_Expenses_getsingle(int id) {
            return base.Channel.Monthly_Expenses_getsingle(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Expenses_getsingleAsync(int id) {
            return base.Channel.Monthly_Expenses_getsingleAsync(id);
        }
        
        public System.Data.DataTable Monthly_Expenses_getall(int id) {
            return base.Channel.Monthly_Expenses_getall(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Expenses_getallAsync(int id) {
            return base.Channel.Monthly_Expenses_getallAsync(id);
        }
        
        public void Monthly_Expenses_repeat(int id, string date, int addprice, bool ispayment) {
            base.Channel.Monthly_Expenses_repeat(id, date, addprice, ispayment);
        }
        
        public System.Threading.Tasks.Task Monthly_Expenses_repeatAsync(int id, string date, int addprice, bool ispayment) {
            return base.Channel.Monthly_Expenses_repeatAsync(id, date, addprice, ispayment);
        }
        
        public System.Data.DataTable Monthly_Expenses_Getmoutcome(int userid, string product, int money, int type, string date1, string date2, int payments, string typegroup, string typestring) {
            return base.Channel.Monthly_Expenses_Getmoutcome(userid, product, money, type, date1, date2, payments, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Expenses_GetmoutcomeAsync(int userid, string product, int money, int type, string date1, string date2, int payments, string typegroup, string typestring) {
            return base.Channel.Monthly_Expenses_GetmoutcomeAsync(userid, product, money, type, date1, date2, payments, typegroup, typestring);
        }
        
        public void Monthly_Expenses_clean_user_data(int id) {
            base.Channel.Monthly_Expenses_clean_user_data(id);
        }
        
        public System.Threading.Tasks.Task Monthly_Expenses_clean_user_dataAsync(int id) {
            return base.Channel.Monthly_Expenses_clean_user_dataAsync(id);
        }
        
        public System.Data.DataTable Monthly_Expenses_get_to_add_price(int userid, string date1, string date2) {
            return base.Channel.Monthly_Expenses_get_to_add_price(userid, date1, date2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Expenses_get_to_add_priceAsync(int userid, string date1, string date2) {
            return base.Channel.Monthly_Expenses_get_to_add_priceAsync(userid, date1, date2);
        }
        
        public int Monthly_Expenses_getaverage(int userid) {
            return base.Channel.Monthly_Expenses_getaverage(userid);
        }
        
        public System.Threading.Tasks.Task<int> Monthly_Expenses_getaverageAsync(int userid) {
            return base.Channel.Monthly_Expenses_getaverageAsync(userid);
        }
        
        public void Monthly_Income_Add(int cpm, string des, int userid, int totalpayed, int numofpay, string date, int type, string typegroup, string typestring) {
            base.Channel.Monthly_Income_Add(cpm, des, userid, totalpayed, numofpay, date, type, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task Monthly_Income_AddAsync(int cpm, string des, int userid, int totalpayed, int numofpay, string date, int type, string typegroup, string typestring) {
            return base.Channel.Monthly_Income_AddAsync(cpm, des, userid, totalpayed, numofpay, date, type, typegroup, typestring);
        }
        
        public System.Data.DataTable Monthly_Income_getall(int userid) {
            return base.Channel.Monthly_Income_getall(userid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Income_getallAsync(int userid) {
            return base.Channel.Monthly_Income_getallAsync(userid);
        }
        
        public System.Data.DataTable Monthly_Income_getspecific(int id) {
            return base.Channel.Monthly_Income_getspecific(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Income_getspecificAsync(int id) {
            return base.Channel.Monthly_Income_getspecificAsync(id);
        }
        
        public void Monthly_Income_Repeat(int ID, string date, int addprice) {
            base.Channel.Monthly_Income_Repeat(ID, date, addprice);
        }
        
        public System.Threading.Tasks.Task Monthly_Income_RepeatAsync(int ID, string date, int addprice) {
            return base.Channel.Monthly_Income_RepeatAsync(ID, date, addprice);
        }
        
        public System.Data.DataTable Monthly_Income_Getmincome(int userid, string des, int cpm, string date1, string date2, int type, string typegroup, string typestring) {
            return base.Channel.Monthly_Income_Getmincome(userid, des, cpm, date1, date2, type, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Income_GetmincomeAsync(int userid, string des, int cpm, string date1, string date2, int type, string typegroup, string typestring) {
            return base.Channel.Monthly_Income_GetmincomeAsync(userid, des, cpm, date1, date2, type, typegroup, typestring);
        }
        
        public void Monthly_Income_change(int monthlyid, int cashpermonth, string description, int totalpay, int numofpay, string dateou, int type, string typegroup, string typestring) {
            base.Channel.Monthly_Income_change(monthlyid, cashpermonth, description, totalpay, numofpay, dateou, type, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task Monthly_Income_changeAsync(int monthlyid, int cashpermonth, string description, int totalpay, int numofpay, string dateou, int type, string typegroup, string typestring) {
            return base.Channel.Monthly_Income_changeAsync(monthlyid, cashpermonth, description, totalpay, numofpay, dateou, type, typegroup, typestring);
        }
        
        public void Monthly_Income_delete(int monthlyid) {
            base.Channel.Monthly_Income_delete(monthlyid);
        }
        
        public System.Threading.Tasks.Task Monthly_Income_deleteAsync(int monthlyid) {
            return base.Channel.Monthly_Income_deleteAsync(monthlyid);
        }
        
        public void Monthly_Income_clean_user_data(int id) {
            base.Channel.Monthly_Income_clean_user_data(id);
        }
        
        public System.Threading.Tasks.Task Monthly_Income_clean_user_dataAsync(int id) {
            return base.Channel.Monthly_Income_clean_user_dataAsync(id);
        }
        
        public System.Data.DataTable Monthly_Income_get_to_add_price(int userid, string date1, string date2) {
            return base.Channel.Monthly_Income_get_to_add_price(userid, date1, date2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Monthly_Income_get_to_add_priceAsync(int userid, string date1, string date2) {
            return base.Channel.Monthly_Income_get_to_add_priceAsync(userid, date1, date2);
        }
        
        public int Monthly_Income_getaverage(int userid) {
            return base.Channel.Monthly_Income_getaverage(userid);
        }
        
        public System.Threading.Tasks.Task<int> Monthly_Income_getaverageAsync(int userid) {
            return base.Channel.Monthly_Income_getaverageAsync(userid);
        }
        
        public void Outcome_History_AddProduct(int userid, int typeid, int price, string product, string date, int ID, string typegroup, string typestring) {
            base.Channel.Outcome_History_AddProduct(userid, typeid, price, product, date, ID, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task Outcome_History_AddProductAsync(int userid, int typeid, int price, string product, string date, int ID, string typegroup, string typestring) {
            return base.Channel.Outcome_History_AddProductAsync(userid, typeid, price, product, date, ID, typegroup, typestring);
        }
        
        public System.Data.DataTable Outcome_History_selectbyuser(int userid) {
            return base.Channel.Outcome_History_selectbyuser(userid);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Outcome_History_selectbyuserAsync(int userid) {
            return base.Channel.Outcome_History_selectbyuserAsync(userid);
        }
        
        public System.Data.DataTable Outcome_History_selectbypro(int id) {
            return base.Channel.Outcome_History_selectbypro(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Outcome_History_selectbyproAsync(int id) {
            return base.Channel.Outcome_History_selectbyproAsync(id);
        }
        
        public System.Data.DataTable Outcome_History_Getproducts(int userid, int typeid, int price, string product, string date1, string date2, int ID, string typegroup, string typestring) {
            return base.Channel.Outcome_History_Getproducts(userid, typeid, price, product, date1, date2, ID, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Outcome_History_GetproductsAsync(int userid, int typeid, int price, string product, string date1, string date2, int ID, string typegroup, string typestring) {
            return base.Channel.Outcome_History_GetproductsAsync(userid, typeid, price, product, date1, date2, ID, typegroup, typestring);
        }
        
        public void Outcome_History_SetProduct(int proid, int typeid, int price, string product, string date, string typegroup, string typestring) {
            base.Channel.Outcome_History_SetProduct(proid, typeid, price, product, date, typegroup, typestring);
        }
        
        public System.Threading.Tasks.Task Outcome_History_SetProductAsync(int proid, int typeid, int price, string product, string date, string typegroup, string typestring) {
            return base.Channel.Outcome_History_SetProductAsync(proid, typeid, price, product, date, typegroup, typestring);
        }
        
        public void Outcome_History_delete(int id) {
            base.Channel.Outcome_History_delete(id);
        }
        
        public System.Threading.Tasks.Task Outcome_History_deleteAsync(int id) {
            return base.Channel.Outcome_History_deleteAsync(id);
        }
        
        public int Outcome_History_get_money(int userid, string date1, string date2) {
            return base.Channel.Outcome_History_get_money(userid, date1, date2);
        }
        
        public System.Threading.Tasks.Task<int> Outcome_History_get_moneyAsync(int userid, string date1, string date2) {
            return base.Channel.Outcome_History_get_moneyAsync(userid, date1, date2);
        }
        
        public int Outcome_History_get_monthly_money(int userid, string date1, string date2) {
            return base.Channel.Outcome_History_get_monthly_money(userid, date1, date2);
        }
        
        public System.Threading.Tasks.Task<int> Outcome_History_get_monthly_moneyAsync(int userid, string date1, string date2) {
            return base.Channel.Outcome_History_get_monthly_moneyAsync(userid, date1, date2);
        }
        
        public System.Data.DataTable Outcome_History_get_monthly_history(int userid, int monthlyid, string date) {
            return base.Channel.Outcome_History_get_monthly_history(userid, monthlyid, date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Outcome_History_get_monthly_historyAsync(int userid, int monthlyid, string date) {
            return base.Channel.Outcome_History_get_monthly_historyAsync(userid, monthlyid, date);
        }
        
        public void Outcome_History_clean_user_data(int id) {
            base.Channel.Outcome_History_clean_user_data(id);
        }
        
        public System.Threading.Tasks.Task Outcome_History_clean_user_dataAsync(int id) {
            return base.Channel.Outcome_History_clean_user_dataAsync(id);
        }
        
        public void Type_Group_Suggestion_add(int userid, string type_group, string comment) {
            base.Channel.Type_Group_Suggestion_add(userid, type_group, comment);
        }
        
        public System.Threading.Tasks.Task Type_Group_Suggestion_addAsync(int userid, string type_group, string comment) {
            return base.Channel.Type_Group_Suggestion_addAsync(userid, type_group, comment);
        }
        
        public System.Data.DataTable Type_Group_Suggestion_select(int id, int userid, string type_group) {
            return base.Channel.Type_Group_Suggestion_select(id, userid, type_group);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Type_Group_Suggestion_selectAsync(int id, int userid, string type_group) {
            return base.Channel.Type_Group_Suggestion_selectAsync(id, userid, type_group);
        }
        
        public System.Data.DataTable Type_Group_Suggestion_getall() {
            return base.Channel.Type_Group_Suggestion_getall();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Type_Group_Suggestion_getallAsync() {
            return base.Channel.Type_Group_Suggestion_getallAsync();
        }
        
        public void Type_Group_Suggestion_delete(int id) {
            base.Channel.Type_Group_Suggestion_delete(id);
        }
        
        public System.Threading.Tasks.Task Type_Group_Suggestion_deleteAsync(int id) {
            return base.Channel.Type_Group_Suggestion_deleteAsync(id);
        }
        
        public void Types_add(string type, string type_group) {
            base.Channel.Types_add(type, type_group);
        }
        
        public System.Threading.Tasks.Task Types_addAsync(string type, string type_group) {
            return base.Channel.Types_addAsync(type, type_group);
        }
        
        public void Types_add_Group(string type_group) {
            base.Channel.Types_add_Group(type_group);
        }
        
        public System.Threading.Tasks.Task Types_add_GroupAsync(string type_group) {
            return base.Channel.Types_add_GroupAsync(type_group);
        }
        
        public System.Data.DataTable Types_gettype(int id, string type) {
            return base.Channel.Types_gettype(id, type);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Types_gettypeAsync(int id, string type) {
            return base.Channel.Types_gettypeAsync(id, type);
        }
        
        public System.Data.DataTable Types_getall() {
            return base.Channel.Types_getall();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Types_getallAsync() {
            return base.Channel.Types_getallAsync();
        }
        
        public int Types_getid(string type, string type_group) {
            return base.Channel.Types_getid(type, type_group);
        }
        
        public System.Threading.Tasks.Task<int> Types_getidAsync(string type, string type_group) {
            return base.Channel.Types_getidAsync(type, type_group);
        }
        
        public string Types_gettypestring(int id) {
            return base.Channel.Types_gettypestring(id);
        }
        
        public System.Threading.Tasks.Task<string> Types_gettypestringAsync(int id) {
            return base.Channel.Types_gettypestringAsync(id);
        }
        
        public bool Types_checkduplicate(string newtype) {
            return base.Channel.Types_checkduplicate(newtype);
        }
        
        public System.Threading.Tasks.Task<bool> Types_checkduplicateAsync(string newtype) {
            return base.Channel.Types_checkduplicateAsync(newtype);
        }
        
        public bool Types_checkduplicategroups(string typegroup) {
            return base.Channel.Types_checkduplicategroups(typegroup);
        }
        
        public System.Threading.Tasks.Task<bool> Types_checkduplicategroupsAsync(string typegroup) {
            return base.Channel.Types_checkduplicategroupsAsync(typegroup);
        }
        
        public System.Data.DataTable Types_get_all_groups() {
            return base.Channel.Types_get_all_groups();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Types_get_all_groupsAsync() {
            return base.Channel.Types_get_all_groupsAsync();
        }
        
        public System.Data.DataTable Types_get_all_types_in_group(string group) {
            return base.Channel.Types_get_all_types_in_group(group);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Types_get_all_types_in_groupAsync(string group) {
            return base.Channel.Types_get_all_types_in_groupAsync(group);
        }
        
        public string Types_get_group(string type) {
            return base.Channel.Types_get_group(type);
        }
        
        public System.Threading.Tasks.Task<string> Types_get_groupAsync(string type) {
            return base.Channel.Types_get_groupAsync(type);
        }
        
        public string Types_gettypegroupstring(int id) {
            return base.Channel.Types_gettypegroupstring(id);
        }
        
        public System.Threading.Tasks.Task<string> Types_gettypegroupstringAsync(int id) {
            return base.Channel.Types_gettypegroupstringAsync(id);
        }
        
        public string Types_gettypeItemstring(int id) {
            return base.Channel.Types_gettypeItemstring(id);
        }
        
        public System.Threading.Tasks.Task<string> Types_gettypeItemstringAsync(int id) {
            return base.Channel.Types_gettypeItemstringAsync(id);
        }
        
        public System.Data.DataTable Types_get_group_table(string type_group) {
            return base.Channel.Types_get_group_table(type_group);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Types_get_group_tableAsync(string type_group) {
            return base.Channel.Types_get_group_tableAsync(type_group);
        }
        
        public System.Data.DataTable Types_get_specific_types(string type, string type_group) {
            return base.Channel.Types_get_specific_types(type, type_group);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Types_get_specific_typesAsync(string type, string type_group) {
            return base.Channel.Types_get_specific_typesAsync(type, type_group);
        }
        
        public void Users_Register(string fname, string lname, string password, int money, string mtype, string date, string email) {
            base.Channel.Users_Register(fname, lname, password, money, mtype, date, email);
        }
        
        public System.Threading.Tasks.Task Users_RegisterAsync(string fname, string lname, string password, int money, string mtype, string date, string email) {
            return base.Channel.Users_RegisterAsync(fname, lname, password, money, mtype, date, email);
        }
        
        public int Users_Login(string email, string password) {
            return base.Channel.Users_Login(email, password);
        }
        
        public System.Threading.Tasks.Task<int> Users_LoginAsync(string email, string password) {
            return base.Channel.Users_LoginAsync(email, password);
        }
        
        public System.Data.DataTable Users_getall() {
            return base.Channel.Users_getall();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Users_getallAsync() {
            return base.Channel.Users_getallAsync();
        }
        
        public string Users_getpassword(int id) {
            return base.Channel.Users_getpassword(id);
        }
        
        public System.Threading.Tasks.Task<string> Users_getpasswordAsync(int id) {
            return base.Channel.Users_getpasswordAsync(id);
        }
        
        public System.Data.DataTable Users_get_specific(string fname, string lname, string pass, int money1, int money2, string moneytype, string date1, string date2, bool admin, string email) {
            return base.Channel.Users_get_specific(fname, lname, pass, money1, money2, moneytype, date1, date2, admin, email);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Users_get_specificAsync(string fname, string lname, string pass, int money1, int money2, string moneytype, string date1, string date2, bool admin, string email) {
            return base.Channel.Users_get_specificAsync(fname, lname, pass, money1, money2, moneytype, date1, date2, admin, email);
        }
        
        public void Users_Change(int id, string fname, string lname, string password, string email) {
            base.Channel.Users_Change(id, fname, lname, password, email);
        }
        
        public System.Threading.Tasks.Task Users_ChangeAsync(int id, string fname, string lname, string password, string email) {
            return base.Channel.Users_ChangeAsync(id, fname, lname, password, email);
        }
        
        public void Users_addmoney(int toadd, int userid, char ioro) {
            base.Channel.Users_addmoney(toadd, userid, ioro);
        }
        
        public System.Threading.Tasks.Task Users_addmoneyAsync(int toadd, int userid, char ioro) {
            return base.Channel.Users_addmoneyAsync(toadd, userid, ioro);
        }
        
        public int Users_getmoney(int id) {
            return base.Channel.Users_getmoney(id);
        }
        
        public System.Threading.Tasks.Task<int> Users_getmoneyAsync(int id) {
            return base.Channel.Users_getmoneyAsync(id);
        }
        
        public System.DateTime Users_get_user_reg_date(int id) {
            return base.Channel.Users_get_user_reg_date(id);
        }
        
        public System.Threading.Tasks.Task<System.DateTime> Users_get_user_reg_dateAsync(int id) {
            return base.Channel.Users_get_user_reg_dateAsync(id);
        }
        
        public bool Users_is_admin(int id) {
            return base.Channel.Users_is_admin(id);
        }
        
        public System.Threading.Tasks.Task<bool> Users_is_adminAsync(int id) {
            return base.Channel.Users_is_adminAsync(id);
        }
        
        public void Users_make_admin(int id) {
            base.Channel.Users_make_admin(id);
        }
        
        public System.Threading.Tasks.Task Users_make_adminAsync(int id) {
            return base.Channel.Users_make_adminAsync(id);
        }
        
        public void Users_nomake_admin(int id) {
            base.Channel.Users_nomake_admin(id);
        }
        
        public System.Threading.Tasks.Task Users_nomake_adminAsync(int id) {
            return base.Channel.Users_nomake_adminAsync(id);
        }
        
        public void Users_clean_user_data(int id) {
            base.Channel.Users_clean_user_data(id);
        }
        
        public System.Threading.Tasks.Task Users_clean_user_dataAsync(int id) {
            return base.Channel.Users_clean_user_dataAsync(id);
        }
        
        public int Users_getallincome(int id) {
            return base.Channel.Users_getallincome(id);
        }
        
        public System.Threading.Tasks.Task<int> Users_getallincomeAsync(int id) {
            return base.Channel.Users_getallincomeAsync(id);
        }
        
        public int Users_getalloutcome(int id) {
            return base.Channel.Users_getalloutcome(id);
        }
        
        public System.Threading.Tasks.Task<int> Users_getalloutcomeAsync(int id) {
            return base.Channel.Users_getalloutcomeAsync(id);
        }
        
        public bool Users_check_email_duplicate(string email) {
            return base.Channel.Users_check_email_duplicate(email);
        }
        
        public System.Threading.Tasks.Task<bool> Users_check_email_duplicateAsync(string email) {
            return base.Channel.Users_check_email_duplicateAsync(email);
        }
        
        public void getaddress(string path) {
            base.Channel.getaddress(path);
        }
        
        public System.Threading.Tasks.Task getaddressAsync(string path) {
            return base.Channel.getaddressAsync(path);
        }
    }
}
